import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { TweenLite, Power3 } from 'gsap/'
import { fromImageToUrl, API_URL } from '../utils/urls'
import { twoDecimals } from '../utils/format'
import Link from 'next/link'
import Dropdown from '../components/Dropdown'
import PaintingShowcase from '../components/PaintingShowcase'
import PrintShowcase from '../components/PrintShowcase'
import WebDevShowcase from '../components/WebDevShowcase'
import { useState } from 'react'
// import { ApolloClient, InMemoryCache, gql } from '@apollo/client';








export default function Home({products, paintings}) {

  const [indexMode, setIndexMode] = useState(1)

  const handleShowcaseMode =()=>{

    if (indexMode == 1) {
      return(
        <PaintingShowcase paintings={paintings}/>
        )
    } else if (indexMode == 2) {
      return(
        <PrintShowcase products={products}/>
        )
    } else if (indexMode == 3){
      return(
        <WebDevShowcase/>
        )
    }


  }


  return (
    <div className="contentContainer">
      <Head>
        <title>Jonathan Pinto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="introContainer">
      Hi, my name is Jonathan and I'm a 
      <Dropdown changeMode={indexMode=>setIndexMode(indexMode)}/>
      </div>

      


    {handleShowcaseMode()}
    

      

      
    </div>
  )
}


export async function getStaticProps(){
  //Fetch the products

  // const client = new ApolloClient({
  //   uri: 'http://localhost:1337/graphql',
  //   cache: new InMemoryCache()
  // });


  const product_res = await fetch(`${API_URL}/products`)
  const products = await product_res.json()

  const painting_res = await fetch(`${API_URL}/paintings`)
  const paintings = await painting_res.json()

  console.log(paintings)

  //Return the products as props

  return {
    props:{
      products,
      paintings
    }
  }

}